DROP DATABASE IF EXISTS verse;
CREATE DATABASE verse;
\c verse

-- USERS
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    password_digest VARCHAR NOT NULL,  
    picture VARCHAR
);

-- AUTORS
CREATE TABLE autor(
    id SERIAL PRIMARY KEY,
    autor_name VARCHAR NOT NULL,
    autor_lastname VARCHAR NOT NULL,
    pen_name VARCHAR,
    picture VARCHAR,
    bio VARCHAR,
    born VARCHAR,
    died VARCHAR,
    birthplace VARCHAR
);

-- BOOKS
CREATE TABLE book(
    id SERIAL PRIMARY KEY,
    cover VARCHAR,
    title VARCHAR NOT NULL,
    serie VARCHAR,
    synopsis VARCHAR,
    published_date VARCHAR,
    pages VARCHAR,
    autor_id INT REFERENCES autor(id) ON DELETE SET NULL,
    genre_id INT REFERENCES autor(id) ON DELETE SET NULL,
    type_id INT REFERENCES type(id) ON DELETE SET NULL,
    status VARCHAR
);

-- GENRES
CREATE TABLE genres(
    id SERIAL PRIMARY KEY,
    genre VARCHAR NOT NULL,
);

-- TYPES OF BOOKS 
CREATE TABLE types_book(
    id SERIAL PRIMARY KEY,
    type VARCHAR NOT NULL,
);

-- REVIEWS 
CREATE TABLE reviews(
    id SERIAL PRIMARY KEY,
    reviewer INT REFERENCES users(id) ON DELETE SET NULL,
    content VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    rating VARCHAR,
    book_id INT REFERENCES book(id) ON DELETE SET NULL
);

-- CREATE TABLE reading_process(
--     id SERIAL PRIMARY KEY,
--     finished BOOLEAN,
--     reading BOOLEAN,
--     untouched BOOLEAN,
--     book_id INT REFERENCES book(id) ON DELETE SET NULL,
--     user_id INT REFERENCES users(id) ON DELETE SET NULL 
-- );

-- FAVORITE LIST
CREATE TABLE fav(
    id SERIAL PRIMARY KEY,
    book_id INT REFERENCES book(id) ON DELETE SET NULL,
    user_id INT REFERENCES users(id) ON DELETE SET NULL 
);

-- BOOKSHELF, FOR FUTURE READING
CREATE TABLE bookshelf_user(
    id SERIAL PRIMARY KEY,
    book_id INT REFERENCES book(id) ON DELETE SET NULL,
    user_id INT REFERENCES users(id) ON DELETE SET NULL 
);

-- INSERTING DATA --
-- USER
INSERT INTO users(name, email, password_digest, picture) VALUES
('Peter Rabbit', 'rabbit@gmail.com', 'ra', 'https://i.pinimg.com/originals/4b/20/df/4b20df5e312c5bc5b5caeb7bcbb3c3bf.jpg'),
('Elios Orphan', 'elios@gmail.com', 'el', 'https://menhairstylesworld.com/wp-content/uploads/2018/01/Two-Tone-Blonde-Hairstyles.jpg'),
('Zylith', 'zylith@gmail.com', 'zy', 'https://format-com-cld-res.cloudinary.com/image/private/s--WXq-dMRr--/c_limit,g_center,h_65535,w_550/a_auto,fl_keep_iptc.progressive,q_95/v1/93d40fb624bc6a78fa460ad2fad45e02/JESSICA-CLEMENTS-CONSTANCE-VICTORIA-EDIT-4web.jpg');

-- AUTOR
INSERT INTO autor(autor_name, autor_lastname, pen_name, picture, bio, born, died, birthplace) VALUES
('Roxanne Longstreet', 'Conrad', 'Rachel Caine', 'https://pbs.twimg.com/profile_images/1177070255937675264/4ymP6L-f_400x400.jpg', 'Rachel Caine is the NYT, USA Today, and #1 WSJ bestselling author of more than 50 books in several categories and genres, including adult thriller and adult urban fantasy/SF as well as books for young adults ages twelve to eighteen. She is the winner of several national awards, and most recently was a finalist in both the International Thriller Writers awards and the Killer Nashville awards for her debut thriller novel Stillhouse Lake.', 'April 27, 1962', null, 'Texas, United States'),
('Jeffery', 'Deaver', null,'https://www.littlebrownspark.com/wp-content/uploads/2017/08/9781455536375_jefferydeaver_spsu17catalog.jpg?resize=500%2C600', '#1 international bestselling author of over thirty novels and three collections of short stories. His first novel featuring Lincoln Rhyme, The Bone Collector, was made into a major motion picture starring Denzel Washington and Angelina Jolie. He''s received or been shortlisted for a number of awards around the world. Deaver was chosen to write a new James Bond novel, Carte Blanche.', 'May 6, 1950', null, 'Illinois, United States'),
('Jessica', 'Bird', 'J. R. Ward', 'http://jrward.com/wp-content/uploads/2019/07/jr_headshot.jpg', 'J.R. Ward is the author of over thirty novels, including those in her #1 New York Times and USA Today bestselling series, The Black Dagger Brotherhood. There are more than 15 million copies of Ward’s novels in print worldwide and they have been published in 25 different countries around the world. Writing has always been her passion and her idea of heaven is a whole day of nothing but her computer, her dog and her coffee pot.', 'April 1969 ', null, 'Massachusetts, United States'),
('María', 'Dueñas', null, 'http://biografias.wiki/wp-content/uploads/2016/07/Mar%C3%ADa-Due%C3%B1as.jpeg', 'Despite her international success, the name María Dueñas once might not have triggered even a flicker of recognition among many U.S. readers. She came into the spotlight in 2009, achieving great success in Spain thanks to her first novel, El tiempo entre costuras, published in English language as The Time in Between and The Seamstress, a historical espionage novel, which sold more than a million copies. But "The Time in Between," an adaptation of her mega-best-selling 2009 novel, has turned into a streaming hit on Netflix', '1964', null, 'Ciudad Real, Spain'),
('Lucy Maud', 'Montgomery', 'L. M. Montgomery', 'https://i.ytimg.com/vi/Kp40JL2EAJU/maxresdefault.jpg', 'A Canadian author best known for a series of novels beginning in 1908 with Anne of Green Gables. The book was an immediate success. Anne Shirley, an orphaned girl, made Montgomery famous in her lifetime and gave her an international following. Montgomery''s work, diaries and letters have been read and studied by scholars and readers worldwide', 'November 30, 1874', 'April 24, 1942',' Clifton (New London), Prince Edward Island, Canada'),
('Edgar Allan', 'Poe', null, 'https://upload.wikimedia.org/wikipedia/commons/9/97/Edgar_Allan_Poe%2C_circa_1849%2C_restored%2C_squared_off.jpg', 'This versatile writer’s oeuvre includes short stories, poetry, a novel, a textbook, a book of scientific theory, and hundreds of essays and book reviews. He is widely acknowledged as the inventor of the modern detective story and an innovator in the science fiction genre, but he made his living as America’s first great literary critic and theoretician. Poe’s reputation today rests primarily on his tales of terror as well as on his haunting lyric poetry.', 'January 19, 1809', 'October 7, 1849', 'Boston, Massachusetts, United States'),
('Anne', 'Patton', null, 'https://images.gr-assets.com/authors/1308431946p5/3301990.jpg', 'Anne Patton’s books for children include Fiddle Dancer and Dancing in My Bones – books that explore Metis culture through the world of dance – and the Tyler collection for Scholastic Education.', null, null, 'Ontario, Canada'),
('John Ronald','Reuel Tolkien', 'J. R. R. Tolkien', 'https://cdn.britannica.com/65/66765-050-63A945A7/JRR-Tolkien.jpg', 'John Ronald Reuel Tolkien, CBE was an English writer, poet, WWI veteran (a First Lieutenant in the Lancashire Fusiliers, British Army), philologist, and university professor, best known as the author of the high fantasy classic works The Hobbit and The Lord of the Rings . The "father" of modern fantasy literature—or more precisely, high fantasy.', '3 January 1892', 'September 02, 1973', 'Bloemfontein, Sudáfrica'),
('Christopher John Reuel', 'Tolkien', 'Christopher Tolkien', 'http://tolkiengateway.net/w/images/thumb/f/ff/Christopher_Tolkien.jpg/250px-Christopher_Tolkien.jpg', 'Is the third son of the author J. R. R. Tolkien. and the editor of much of his father''s posthumously published work. He drew the original maps for his father''s The Lord of the Rings, which he signed C. J. R. T. After his father''s death, Christopher Tolkien embarked on organizing the masses of his father''s notes, some of them written on odd scraps of paper a half-century earlier.', '21 November 1924', null, 'Leeds, England, United Kingdom'),
('Paula', 'Hawkins', 'Amy Silver', 'https://www.thetimes.co.uk/imageserver/image/methode%2Ftimes%2Fprodmigration%2Fweb%2Fbin%2Ff23bca2d-3b0c-30a7-9031-9a807ef67fa1.jpg?crop=780%2C520%2C0%2C0&resize=685', 'Paula Hawkins is the author of the #1 New York Times bestseller The Girl on the Train, which was made into a major motion picture. Her new novel of psychological suspense, Into The Water, was released in 2017.', '26 August 1972', null, 'Salisbury, Rhodesia (now Harare, Zimbabwe)'),
('Joanne','Rowling', 'J.K. Rowling', 'https://www.milenio.com/uploads/media/2019/07/31/j-k-rowling-facebook.jpg', 'Is a British author, film producer, television producer, screenwriter, and philanthropist. She is best known for writing the Harry Potter fantasy series, which has won multiple awards and sold more than 500 million copies, becoming the best-selling book series in history. Anticipating that the target audience of young boys might not want to read a book written by a woman, her publishers demanded that she use two initials, rather than her full name. As she had no middle name, she chose K as the second initial of her pen name, from her paternal grandmother Kathleen Ada Bulgen Rowling. As a child, Rowling often wrote fantasy stories, which she would usually then read to her sister. ', '31 July 1965', null, 'Yate, Gloucestershire, England'),
('Stephen Edwin', 'King','Stephen King', 'http://w1.muyvirtual.com/var/ezdemo_site/storage/images/entretenimiento/farandula/!de-terror!-stephen-edwin-king/7958-4-esl-ES/!De-terror!-Stephen-Edwin-King_articleimage.jpg', 'Is an American author of horror, supernatural fiction, suspense, and fantasy novels. His books have sold more than 350 million copies, many of which have been adapted into feature films, miniseries, television series, and comic books. He has been described as the "King of Horror". Stephen made his first professional short story sale ("The Glass Floor") to Startling Mystery Stories in 1967.', 'September 21, 1947', null, 'Portland, Maine, The United States'),
('Dumas', 'Davy de la Pailleterie', 'Alexandre Dumas', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Alexander_Dumas_p%C3%A8re_par_Nadar_-_Google_Art_Project.jpg/1200px-Alexander_Dumas_p%C3%A8re_par_Nadar_-_Google_Art_Project.jpg','Best known for his numerous historical novels of high adventure which have made him one of the most widely read French authors in the world. His father, General Thomas-Alexandre Dumas Davy de la Pailleterie, was born in the French colony of Saint-Domingue (present-day Haiti) to Alexandre Antoine Davy de la Pailleterie, a French nobleman, and Marie-Cessette Dumas, a black slave. At age 14 Thomas-Alexandre was taken by his father to France.', 'July 24, 1802', 'December 05, 1870', 'Villers-Cotterêts, Aisne, France'),
('Maja Stina', 'Walter', 'Maria Gripe', 'https://images.gr-assets.com/authors/1300035928p8/42162.jpg', 'was a Swedish author of books for children and young adults, which were often written in magical and mystical tone.  In 1946 she married the artist Harald Gripe, who created cover illustrations for most of her books. His illustration career, in fact, began in connection with his wife''s debut as author of I vår lilla stad ("In our little town"). Much of her writing, particularly the later works, is suffused with a supernatural or mystical element. This change in her writing style from her less mature work was partly a result of the influence of Edgar Allan Poe, Charlotte and Emily Brontë, and Carl Jonas Love Almquist. A prominent feature of Maria Gripe''s writing is a respect for individuals and their unique characteristics,', '25 July 1923', '5 April 2007', 'Vaxholm, Sweden'),
('Isabel', 'Allende Llona', 'Isabel Allende', 'https://www.elpuntavui.cat/imatges/58/88/alta/780_0008_5888389_8a35ff9cc51d9dbab9b736f5c7c267e6.jpg', 'Is a Chilean writer. Allende, who writes in the "magic realism" tradition, is considered one of the first successful women novelists in Latin America. She has written novels based in part on her own experiences, often focusing on the experiences of women, weaving myth and realism together. She has lectured and done extensive book tours and has taught literature at several US colleges.', '2 August 1942', null, 'Lima, Peru');


-- BOOK
INSERT INTO book(cover, title, serie, synopsis, published_date, pages, autor_id) VALUES
('https://images-na.ssl-images-amazon.com/images/I/81GpfcTiJAL.jpg', 'Glass Houses', 'The Morganville Vampires #1', 'College freshman Claire Danvers has had enough of her nightmarish dorm situation, where the popular girls never let her forget just where she ranks in the school’s social scene: somewhere less than zero. When Claire heads off-campus, the imposing old house where she finds a room may not be much better. Her new roommates don’t show many signs of life. But they’ll have Claire’s back when the town’s deepest secrets come crawling out, hungry for fresh blood.', 'Oct 03, 2006', '256', 1),
('https://images-na.ssl-images-amazon.com/images/I/81G9sBK-XIL.jpg', 'The Dead Girls’ Dance', 'The Morganville Vampires #2', 'Claire has her share of challenges. Like being a genius in a school that favors beauty over brains; homicidal girls in her dorm, and finding out that her college town is overrun with the living dead. On the up side, she has a new boyfriend with a vampire-hunting dad. But when a local fraternity throws the Dead Girls’ Dance, hell is really going to break loose.', 'Aug 17, 2009', '256', 1),
('https://images-na.ssl-images-amazon.com/images/I/81GDvEouFyL.jpg', 'Midnight Alley', 'The Morganville Vampires #3', 'MORGANVILLE IS SUCH A NICE PLACE TO LIVE... AND DIE. IF YOU DON''T MIND THAT SORT OF THING. When Claire Danvers learnt that her college town was run by vampires, she did what any intelligent, self-preserving student would do: she applied for a transfer and stocked up on garlic. The transfer is no longer an option, but that garlic may come in handy. Now Claire has pledged herself to Amelie, the most powerful vampire in town. The protection her contract secures does little to reassure her friends. All of a sudden, people are turning up dead, a stalker resurfaces from Claire''s past, and an ancient bloodsucker extends a chilling invitation for private lessons in his secluded home.', ' October 2, 2007','245', 1),
('https://images-na.ssl-images-amazon.com/images/I/81E20eOsXJL.jpg', 'Feast of Fools', 'The Morganville Vampires #4', 'In the town of Morganville, vampires and humans live in relative peace. Student Claire Danvers has never been convinced, though, especially with the arrival of Mr. Bishop, an ancient, old-school vampire who cares nothing about harmony. What he wants from the town''s living and its dead is unthinkably sinister. It''s only at a formal ball, attended by vampires and their human dates, that Claire realizes the elaborately evil trap he''s set for Morganville', ' June 3, 2008', '242', 1),
('https://images-na.ssl-images-amazon.com/images/I/81RDGxV49FL.jpg', 'Lord of Misrule', 'The Morganville Vampires #5', 'In the college town of Morganville, vampires and humans coexist in (relatively) bloodless harmony. Then comes Bishop, the master vampire who threatens to abolish all order, revive the forces of the evil dead, and let chaos rule. But Bishop isn''t the only threat. Violent black cyclone clouds hover, promising a storm of devastating proportions as student Claire Danvers and her friends prepare to defend Morganville against elements both natural and unnatural.', ' January 2009', '246', 1),
('https://images-na.ssl-images-amazon.com/images/I/81bBbrAAJxL.jpg', 'Carpe Corpus', 'The Morganville Vampires #6', 'In the small college town of Morganville, vampires and humans lived in (relative) peace-until all the rules got rewritten when the evil vampire Bishop arrived, looking for the lost book of vampire secrets. He''s kept a death grip on the town ever since. Now an underground resistance is brewing, and in order to contain it, Bishop must go to even greater lengths. He vows to obliterate the town and all its inhabitants-the living and the undead. Claire Danvers and her friends are the only ones who stand in his way. But even if they defeat Bishop, will the vampires ever be content to go back to the old rules, after having such a taste of power?', 'June 2, 2009', '241', 1),
('https://i.ebayimg.com/images/g/HO8AAOSwImRYf4gQ/s-l1600.jpg', ' Fade Out','The Morganville Vampires #7', 'Withoutthe evil vampire Bishop ruling over the town of Morganville,the resident vampires have made major concessions to the human population. With their newfound freedoms, Claire Danvers and her friends are almost starting to feel comfortable again… Now Claire can actually concentrate on her studies, and her friend Eve joins the localtheatrecompany. But when one of Eve’s castmates goes missingafter starting work on a shortdocumentary, Eve suspects the worst. Claire and Eve soon realize that this film project, whose subjectis the vampires themselves, is a wholelot bigger—andway more dangerous—than anyone suspected.', 'November 3, 2009', '237', 1),
('https://images-na.ssl-images-amazon.com/images/I/81rB5e-%2Bl5L.jpg', ' Kiss of Death', 'The Morganville Vampires #8', 'Vampire musician Michael Glass has attracted the attention of a big- time producer who wants to cut a demo and play some gigs-which means Michael will have to enter the human world. For this, he''s been assigned escorts that include both a dangerous immortal as well as Michael''s all-too-human friends. And with that mix of personalities, this is going to be a road trip from hell...', 'April 27, 2010', '246 ', 1),
('https://images-na.ssl-images-amazon.com/images/I/81uJFXiSUEL.jpg', 'Ghost Town', 'The Morganville Vampires #9', 'While developing a new system to maintain the town''s defenses, Claire discovers a way to use the vampires'' powers to help keep outsiders from spreading news of Morganville''s "unique" situation once they''ve crossed the city limits. But the new system has an unexpected and possibly deadly consequence: People inside the town start forgetting who and what they are - even the vampires. And when Claire''s boyfriend, Shane, and her best friend, Eve, start treating her like a perfect stranger, Claire realizes she has to figure out a way to pull the plug on her experiment - before she forgets how to save herself... and Morganville. ', 'November 2010', '335', 1),
('https://images-na.ssl-images-amazon.com/images/I/81dkhZTl5fL.jpg', 'Bite Club', 'The Morganville Vampires #10', 'After discovering that vampires populate her town, college student Claire Danvers knows that the undead just want to live their lives. But someone else wants them to get ready to rumble. There''s a new extreme sport getting picked up on the Internet: bare—knuckle fights pitting captured vampires against each other—or humans. Tracking the remote signal leads Claire—accompanied by her friends and frenemies—to discover that what started as an online brawl will soon threaten everyone in Morganville...', 'May 3, 2011', '340', 1),
('https://images-na.ssl-images-amazon.com/images/I/91PaWHfEkWL.jpg', 'Last Breath', 'The Morganville Vampires #11', 'With her boss preoccupied researching the Founder Houses in Morganville, student Claire Danvers is left to her own devices when she learns that three vampires have vanished without a trace. She soon discovers that the last person seen with one of the missing vampires is someone new to town-a mysterious individual named Magnus. After an uneasy encounter with Morganville''s latest resident, Claire is certain Magnus isn''t merely human. But is he a vampire-or something else entirely?', ' November 1, 2011', '335', 1),
('https://images-na.ssl-images-amazon.com/images/I/81N603q8gGL.jpg', 'Black Dawn', 'The Morganville Vampires #12', 'Ever since the draug—mysterious creatures that prey on vampires—took over Morganville, the lives of student Claire Danvers and her friends have been thrown into turmoil. Most of the town’s residents have evacuated, but Claire, Shane, Eve and Michael have chosen to stay and fight.Using the city’s water system to spread, the draug have rapidly multiplied. Things in Morganville look grim, especially since vampire Amelie—the town founder—has been infected by the master draug’s bite. Now, if Claire and her friends don’t figure out how to cure Amelie and defeat the draug, it looks like Morganville will become little more than a ghost town… ', 'May 1, 2012', '367', 1),
('https://images-na.ssl-images-amazon.com/images/I/81sCpcm-qML.jpg', 'Bitter Blood', 'The Morganville Vampires #13', 'Thanks to the eradication of the parasitic creatures known as the draug, the vampires of Morganville have been freed of their usual constraints. With the vampires indulging their every whim, the town’s human population is determined to hold on to their lives by taking up arms. But college student Claire Danvers isn’t about to take sides, considering she has ties to both the humans and the vampires. To make matters worse, a television show comes to Morganville looking for ghosts, just as vampire and human politics collide. Now, Claire and her friends have to figure out how to keep the peace without ending up on the nightly news… or worse.', ' November 6, 2012', '404', 1),
('https://images-na.ssl-images-amazon.com/images/I/81DK5k54lJL.jpg', 'Fall of Night', 'The Morganville Vampires #14', 'Claire thought she''d never get to leave Morganville, but she can''t pass up the chance to finally attend her dream school, MIT. After all, getting to invent anti-vamp devices with Professor Anderson - a Morganville exile herself - sounds like a dream come true... until Claire realizes there are sinister forces at play, and she''s not the only one with a vampire-related agenda. Without her friends Shane, Eve, and Michael, Claire finds that surviving a killer schedule may be hard... but with them, it might turn out to be impossible.', 'May 7th 2013', '352', 1),
('https://images-na.ssl-images-amazon.com/images/I/81I-GSF%2BnuL.jpg', 'Daylighters', 'The Morganville Vampires #15', 'While Morganville, Texas, is often a troubled town, Claire Danvers and her friends are looking forward to coming home. But the Morganville they return to isn’t the one they know; it’s become a different place—a deadly one… Something drastic has happened in Morganville while Claire and her friends were away. The town looks cleaner and happier than they’ve ever seen it before, but when their incoming group is arrested and separated—vampires from humans—they realize that the changes definitely aren’t for the better. It seems that an organization called the Daylight Foundation has offered the population of Morganville something they’ve never had: hope of a vampire-free future. And while it sounds like salvation—even for the vampires themselves—the truth is far more sinister and deadly. Now, Claire, Shane and Eve need to find a way to break their friends out of Daylighter custody, before the vampires of Morganville meet their untimely end…', ' November 5, 2013', '368', 1),
('https://images-na.ssl-images-amazon.com/images/I/71dpnJonsVL.jpg','The Bone Collector','Lincoln Rhyme #1', 'Lincoln Rhyme, ex-head of NYPD forensics, was the nation’s foremost criminalist, the man who could work a crime scene and come away with a perfect profile of the killer, frozen in time. Now, Lincoln is frozen in place — permanently. An accident on the job left him a quadriplegic who can move just one finger, a great mind strapped to his bed, mulish and sarcastic, hiding from a life he no longer wants to live. Until he sees the crime-scene report about a corpse found buried on a deserted West Side railroad track, its bloody hand rising from the dirt. It belonged to a man who got into a cab at the airport and never got out. Reluctantly, Lincoln Rhyme abandons retirement to track down a killer whose ingenious clues hold the secret to saving his victims — if Rhyme can decipher them in time. The search leads him to the Bone Collector, whose obsession with old New York colors every scrap of evidence he leaves for Rhyme and his new partner, Amelia Sachs, whom he drafts as his arms and legs. But she’s never worked a crime scene in her life — and he can only whisper in her ear as she does the exacting work he loved more than anything else. The movie adaptation of The Bone Collector, starring Denzel Washington and Angelina Jolie, was made by Universal Pictures in 1999.', '1997', '528', 2),
('https://www.jefferydeaver.com/wp-content/uploads/2013/01/The-Coffin-Dancer-800x1218.jpg', 'The Coffin Dancer', 'Lincoln Rhyme #2', 'Detective Lincoln Rhyme, the foremost criminalist in the NYPD, is put on the trail of the Coffin Dancer, a cunning professional killer who has continually eluded the police. Rhymes —-a quadriplegic since a line-of-duty accident — must use his wits to track this brilliant killer who’s been hired to eliminate three witnesses in the last hours before their grand jury testimony. Rhyme works with his eyes and ears, New York City cop Amelia Sachs, to gather information from trace evidence at the crime scene to nail him, or at least to predict his next move and head him off. So far, they have only one clue: the assassin has a tattoo on his arm of the Grim Reaper waltzing with a woman in front of a coffin.', 'August 15th 1998', '532', 2),
('https://www.jefferydeaver.com/wp-content/uploads/2013/01/The-Empty-Chair-800x1218.jpg', 'The Empty Chair', 'Lincoln Rhyme #3', 'Lincoln Rhyme is back… This spine-chilling new thriller pits renowned criminalist Lincoln Rhyme against the ultimate opponent — Amelia Sachs, his own brilliant protégée. A quadriplegic since a beam crushed his spinal cord years ago, Rhyme is desperate to improve his condition and goes to the University of North Carolina Medical Center for high-risk experimental surgery. But he and Sachs have hardly settled in when the local authorities come calling. In a twenty-four-hour period, the sleepy Southern outpost of Tanner’s Corner has seen a local teen murdered and two young women abducted. And Rhyme and Sachs are the best chance to find the girls alive. The prime suspect is a strange teenaged truant known as the Insect Boy, so nicknamed for his disturbing obsession with bugs. Rhyme agrees to find the boy while awaiting his operation. Rhyme’s unsurpassed analytical skills and stellar forensic experience, combined with Sachs’s exceptional detective legwork, soon snare the perp. But even Rhyme can’t anticipate that Sachs will disagree with his crime analysis and that her vehemence will put her in the swampland, harboring the very suspect whom Rhyme considers a ruthless killer. So ensues Rhyme’s greatest challenge — facing the criminalist whom he has taught everything he knows in a battle of wits, forensics, and intuition. And in this adversary, Rhyme also faces his best friend and soul mate.', 'May 9, 2000', 416, 2),
( 'https://www.jefferydeaver.com/wp-content/uploads/2013/01/The-Stone-Monkey-800x1218.jpg', 'The Stone Monkey', 'Lincoln Rhyme #4','Recruited to help the FBI and the Immigration and Naturalization Service perform the nearly impossible, Lincoln Rhyme and his partner, Amelia Sachs, manage to track down a cargo ship headed for New York City carrying two dozen illegal Chinese immigrants, as well as the notorious human smuggler and killer known as “the Ghost.” But when the Ghost’s capture goes disastrously wrong, Lincoln and Amelia find themselves in a race against time: to stop the Ghost before he can track down and murder the two surviving families who have escaped from the ship and vanished deep into the labyrinthine world of New York City’s Chinese community. Over the next harrowing forty-eight hours, the Ghost brilliantly and ruthlessly hunts for the families, while Rhyme, aided by a quirky policeman from mainland China, struggles to find them before they die, and Amelia Sachs pursues a very different kind of police work — forming a connection with one of the immigrants that may affect her relationship with her partner and lover, Lincoln Rhyme.', 'March 12, 2002', ' 657', 2),
('https://www.jefferydeaver.com/wp-content/uploads/2013/01/The-Vanished-Man-800x1218.jpg', 'The Vanished Man', 'Lincoln Rhyme #5', 'It begins at a prestigious music school in New York City. A killer flees the scene of a homicide and locks himself in a classroom. Within minutes, the police have him surrounded. When a scream rings out, followed by a gunshot, they break down the door. The room is empty. Lincoln Rhyme and Amelia Sachs are brought in to help with the high-profile investigation. For the ambitious Sachs, solving the case could earn her a promotion. For the quadriplegic Rhyme, it means relying on his protégée to ferret out a master illusionist they’ve dubbed “the conjurer” who baits them with gruesome murders that become more diabolical with each fresh crime. As the fatalities rise and the minutes tick down, Rhyme and Sachs must move beyond the smoke and mirrors to prevent a terrifying act of vengeance that could become the greatest vanishing act of all.', 'March 11, 2003', '560', 2),
('https://www.jefferydeaver.com/wp-content/uploads/2013/01/The-Twelfth-Card-1-800x1218.jpg','The Twelfth Card', 'Lincoln Rhyme #6', 'A high-school girl in Harlem, Geneva Settle, is the target of a ruthless professional killer—Thompson Boyd—who has been hired to murder her for reasons unknown. His first attempt, in a deserted museum early one morning, is a failure but it’s clear to Lincoln Rhyme that he’s going to strike again, from clues the killer leaves behind, one of which is the twelfth card in the tarot deck, The Hanged Man, whose meaning resonates eerily throughout the story. Assisted by Fred Dellray, Mel Cooper and Lon Sellitto (suffering from a severe case of shattered nerves due to a near miss by the killer), Rhyme and partner Amelia Sachs work frantically to learn who the hit man and his partner are and when they will strike next, all the while trying to crack a very “cold” case: Rhyme believes that Geneva may have been targeted because of a paper she’s writing about her ancestor, Charles Singleton, a former slave who was instrumental in the civil rights movement in the 1860s, but who was arrested for theft and disgraced. In his correspondence Charles wrote about a “secret,” that could have tragic consequences if revealed. This secret, which Rhyme is convinced will provide the key to why Geneva is in danger, revolves around some mysterious doings in the area known as Gallows Heights, a neighborhood on the Upper West Side of Manhattan that in the 1860s was a tense mix of wealthy financiers, civil rights leaders, political crooks like Boss Tweed, and working-class laborers and thugs. What was the truth behind the crime Charles was accused of? And what was his secret? Does it have to do with stolen gold? Or does it have a far broader implications?', 'June 7, 2005', '816', 2 ),
('https://www.jefferydeaver.com/wp-content/uploads/2013/01/The-Cold-Moon-800x1218.jpg','The Cold Moon ', 'Lincoln Rhyme #7','Lincoln Rhyme returns in The Cold Moon, a roller coaster of a thriller that pits Lincoln and Amelia Sachs against time itself. On a freezing December night, with a full moon hovering in the black skies over New York City, two people are brutally murdered—their prolonged deaths marked by eerie calling-cards: moon-faced clocks ticking away the victims’ last minutes on earth.  More murders are planned, and Rhyme and his team have only hours to stop the icy-cold, brilliant Watchmaker, whose obsession with time drives him to plan his carnage with the precision of a fine timepiece. While the cat-and-mouse search for the killer proceeds, Amelia Sachs must balance her efforts to catch the Watchmaker with her job as lead detective on the first homicide case of her own, in which she unearths shocking revelations from the past that threaten to undermine her very relationship with Lincoln Rhyme. An unlikely ally appears on the scene in the form of California Bureau of Investigation special agent Kathryn Dance, one of the nation’s leading experts in interrogation and kinesics—body language. Despite Lincoln’s skepticism about witnesses, and her distrust of physical evidence, the two form a curious alliance in the heart-stopping quest to find the Watchmaker. The rest of the team is present too—tech-minded Mel Cooper, dogged Lon Sellitto, hip Fred Dellray, and the newest addition: rookie Ron Pulaski. Deaver’s lightning-fast prose keeps the two cases racing along in almost real time, with more plot twists and surprises than in any previous book of his, as we realize that the Watchmaker may not be simply a murderous lunatic, but a far more cunning villain than anyone could guess, and the most terrifying and mesmerizing bad guy to ever come from the mind of Jeffery Deaver.', ' June 26, 2006', '416 ', 2),
('https://www.jefferydeaver.com/wp-content/uploads/2013/01/TheBrokenWindow.jpg','The Broken Window ', 'Lincoln Rhyme #8', 'Quadriplegic detective Lincoln Rhyme is back in a chilling new thriller from the master of suspense, Jeffery Deaver. When Rhyme’s cousin is accused of murder, he and partner Amelia Sachs return to face a criminal whose ingenious staging of crimes is enabled by a terrifying access to information… When Lincoln’s estranged cousin Arthur Rhyme is arrested on murder charges, the case is perfect—too perfect. Forensic evidence from Arthur’s home is found all over the scene of the crime, and it looks like the fate of Lincoln’s relative is sealed. At the behest of Arthur’s wife, Judy, Lincoln grudgingly agrees to investigate the case. Soon Lincoln and Amelia uncover a string of similar murders and rapes with perpetrators claiming innocence and ignorance—despite ironclad evidence at the scenes of the crime. Rhyme’s team realizes this “perfect” evidence may actually be the result of masterful identity theft and manipulation. An information service company—the huge data miner Strategic Systems Datacorp—seems to have all the answers but is reluctant to help the police. Still, Rhyme and Sachs and their assembled team begin uncovering a chilling pattern of vicious crimes and cover-ups, and their investigation points to one master criminal, whom they dub “522.” When “522” learns the identities of the crime-fighting team, the hunters become the hunted. Full of Deaver’s trademark plot twists, The Broken Window will put the partnership of Lincoln Rhyme and Amelia Sachs to the ultimate test.', 'June 10, 2008', '414', 2),
('https://www.jefferydeaver.com/wp-content/uploads/2013/01/The-Burning-Wire-800x1218.jpg','The Burning Wire', 'Lincoln Rhyme #9', 'Lincoln Rhyme is back, on the trail of a killer whose weapon of choice cripples New York City with fear. The weapon is invisible and omnipresent.  Without it, modern society grinds to a halt.  It is the electrical grid.  The killer harnesses and steers huge arc flashes with voltage so high, and heat so searing, that steel melts and his victims are set afire, or subtly reconnects a few wires in one’s house or office so that the bathtub, the sink, the computer keyboard, the simple desk lamp can kill. When the first horrific attack occurs in broad daylight, reducing a city bus to a pile of molten, shrapnel-riddled metal, officials fear terrorism.  Rhyme, a world-class forensic criminologist known for his successful apprehension of the most devious criminals, is immediately tapped for the investigation.  Long a quadriplegic, he assembles NYPD detective Amelia Sachs and officer Ron Pulaski as his eyes and ears and legs on crime sites, and FBI agent Fred Dellray as his undercover man on the street.  As the attacks continue across the city at a sickening pace, and terrifying demand letters begin appearing, the team works desperately against time and with maddeningly little forensic evidence to try to find the killer.   Or is it killers….? Meanwhile, Rhyme is consulting on another high-profile investigation in Mexico with a most coveted quarry in his cross-hairs:  the hired killer known as the Watchmaker, one of the few criminals to have eluded Rhyme’s net. Juggling two massive investigations against a cruel ticking clock takes a toll on Rhyme’s health.  Soon Rhyme is fighting on yet another front — and his determination to work despite his physical limitations threatens to drive away his closest allies when he needs them most.', ' June 1, 2010', ' 414 ', 2),
('https://www.hodder.co.uk/wp-content/uploads/2019/04/hbg-title-9781444778960-2.jpg?fit=1524%2C2339', 'A Textbook Case', 'Lincoln Rhyme #9.5', 'From Jeffery Deaver--the New York Times bestselling author of the upcoming Lincoln Rhyme novel THE KILL ROOM (on sale June 4, 2013)--comes an original short story featuring Rhyme. When a young woman is found brutally murdered in a parking garage, with a veritable mountain of potential evidence to sift through, it may be the most challenging case former NYPD detective Lincoln Rhyme has ever taken on.', 'April 2nd 2013', '45', 2),
('https://www.jefferydeaver.com/wp-content/uploads/2012/12/TheKillRoom2016.jpg', 'The Kill Room', 'Lincoln Rhyme #10', 'Robert Moreno, an American citizen living in South America, is shot in the Bahamas by a sniper. The killing was commissioned by the U.S. government, who received a tip-off that Moreno was planning a terrorist attack on a U.S. oil company headquarters. But this intelligence was fatally incorrect: anti-American Moreno ordered a protest at the oil company, not an attack. Lincoln Rhyme and Amelia Sachs are drafted in to investigate. While Sachs traces Moreno’s steps in New York, Rhyme travels to the scene of the crime in Nassau, where he finds himself on a dangerous path trailed by the sniper himself. As details of the case start to emerge, the pair discover that not all is what it seemed. Can they achieve justice and escape with their lives intact?', 'June 20, 2013', '456', 2),
('https://www.jefferydeaver.com/wp-content/uploads/2013/12/TheSkinCollector2016.jpg', 'The Skin Collector', 'Lincoln Rhyme #11', 'They call this butcher The Skin Collector: a tattooist with a chamber of torture hidden deep underground. But instead of using ink to create each masterpiece, the artist uses a lethal poison which will render targets dead before they can even entertain the prospect of escape . . . Drafted in to investigate, NYPD detective Lincoln Rhyme and his associate Amelia Sachs have little to go on but a series of cryptic messages left etched into the skin of the deceased. As the pair struggle to discover the meaning behind the designs, they are led down a treacherous and twisting path where nothing is as it seems. And with the clock rapidly ticking before the killer strikes again, they must untangle the twisted web of clues before more victims – or they themselves – are next.', 'May 13th 2014', ' 430', 2),
('https://kbimages1-a.akamaihd.net/85d037f1-6c87-49d2-9a69-8e09dcf4e830/1200/1200/False/the-deliveryman.jpg', 'The Deliveryman', 'Lincoln Rhyme #11.5', 'A Lincoln Rhyme Short Story A man is murdered in a back alley. Renowned forensic detective Lincoln Rhyme and his partner Amelia Sachs are left with a veritable mountain of evidence collected from the trash-filled alley, and their only lead is a young eyewitness: the man''s eight-year-old son, who was riding along on his father''s delivery route. But the murder victim may have been more than just a simple deliveryman. Rhyme and Sachs uncover clues that he might have been delivering a highly illegal, contraband shipment--which is now missing. And someone wants it back...', 'February 2nd 2016', '75', 2),
('https://www.jefferydeaver.com/wp-content/uploads/2015/08/TheSteelKissMM.jpg', 'The Steel Kiss', 'Lincoln Rhyme #12', 'Amelia Sachs is hot on the trail of a killer. She’s chasing him through a department store in Brooklyn when an escalator malfunctions. The stairs give way, with one man horribly mangled by the gears. Sachs is forced to let her quarry escape as she jumps in to try to help save the victim. She and famed forensic detective Lincoln Rhyme soon learn, however, that the incident may not be an accident at all, but the first in a series of intentional attacks. They find themselves up against one of their most formidable opponents ever: a brilliant killer who turns common products into murder weapons. As the body count threatens to grow, Sachs and Rhyme must race against the clock to unmask his identity–and discover his mission–before more people die.', 'March 8th 2016', '486', 2),
('https://www.jefferydeaver.com/wp-content/uploads/2016/08/The-Burial-Hour.jpg', 'The Burial Hour', 'Lincoln Rhyme #13', 'A traveling businessman is snatched off of an Upper East Side street in broad daylight–or so it appears to the nine-year-old girl who is the crime’s only witness. The perp leaves a token at the site of the kidnapping–a miniature noose. A crime scene this puzzling demands forensic expertise of the highest order. Lincoln Rhyme and Amelia Sachs are called in to investigate. Rhyme and Sachs’ investigation takes an unexpected turn when a similar kidnapping occurs across the Atlantic in a small town outside of Naples, Italy. The killer’s M.O. is bizarre and frightening. Obsessed with music, the man records the final breaths of his victims, then uses a keyboard sampler to compose an otherworldly tune that is then posted online. The search for the killer will become a complex case of international cooperation–yet not all is as it seems, and soon Sachs and Rhyme find themselves playing a dangerous game with shadowy parties from across the globe.', 'April 11th 2017 ', '480', 2),
('https://www.jefferydeaver.com/wp-content/uploads/2017/08/The-Cutting-Edge-2.jpg', 'The Cutting Edge', 'Lincoln Rhyme #14', 'Lincoln Rhyme and Amelia Sachs return to New York City to confront a killer terrorizing couples at their happiest and most vulnerable. In the early hours of a quiet, weekend morning in Manhattan’s Diamond District, a brutal triple murder shocks the city. Lincoln Rhyme and Amelia Sachs quickly take the case. Curiously, the killer has left behind a half-million dollars’ worth of gems at the murder scene, a jewelry store on 47th street. As more crimes follow, it becomes clear that the killer’s target is not gems, but engaged couples themselves. The Promisor vows to take the lives of men and women during their most precious moments-midway through the purchase of an engagement ring, after a meeting with a wedding planner, trying on the perfect gown for a day that will never come. The Promisor arrives silently, armed with knife or gun, and a time of bliss is transformed, in an instant, to one of horror. Soon the Promiser makes a dangerous mistake: leaving behind an innocent witness, Vimal Lahori, a talented young diamond cutter, who can help Rhyme and Sachs blow the lid off the case. They must track down Vimal before the killer can correct his fatal error. Then disaster strikes, threatening to tear apart the very fabric of the city-and providing the perfect cover for the killer to slip through the cracks.', 'April 10th 2018', '434', 2);

-- GENRE
INSERT INTO genres(type, book_id, autor_id) VALUES
('SciFi', 1, 1),
('horror', 1, 1),
('Mystery', 1, 1),
('Thriller', 18, 2),
('Crime', 16, 2);

-- TYPES
INSERT INTO types_book(type, book_id) VALUES
('book', 1),
('book', 2),
('book', 3),
('book', 4),
('book', 5),
('book', 6),
('book', 7),
('book', 8);

-- REVIEWS
INSERT INTO reviews(reviewer, content, created_at, rating, book_id) VALUES
(1, 'This book surprised me.  I expected to like it – I enjoy vampire and paranormal fiction.  And yet I didn’t think I would like it as much as I did.', '2014-07-02 06:14:00.742000000', '5', 1),
(3, 'The pace of the story is good and the book itself is well-written.  The characters are engaging, and the main ones, Claire, Eve, Michael and Shane are likeable.', '2018-07-10 03:10:00.742000000', '4.5', 1),
(2, 'If you enjoy vampire novels, you will probably enjoy this, but be warned it is aimed at teenagers / young adults.  Adult themes are kept to a minimum, and gore levels are also low.', '2019-12-10 07:10:00.742000000', '5', 1),
(1, 'Author Deaver is just as cunning and deceptive as his killer.', '2019-06-1 09:10:00.722000000', '4', 16);

-- READING PROCESS
INSERT INTO reading_process(finished, reading, untouched, book_id, user_id) VALUES
(true, null, false, 1, 1),
(false, true, false, 1, 2);

-- FAVs
INSERT INTO fav(book_id, user_id) VALUES
('1', '1');

INSERT INTO bookshelf_user(book_id, user_id) VALUES
('1', '1');
